# Generated by Django 3.1.1 on 2020-09-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=36)),
                ('temperature', models.FloatField()),
                ('rec_at', models.CharField(max_length=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
