# Generated by Django 3.1.1 on 2020-09-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='at',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='mac',
        ),
        migrations.AddField(
            model_name='reading',
            name='device_id',
            field=models.CharField(db_index=True, default=0, max_length=50),
        ),
    ]
